services:
  db:
    image: postgres:14
    container_name: celebot_db
    environment:
      POSTGRES_USER: celebot_admin
      POSTGRES_PASSWORD: meow-password
      POSTGRES_DB: celebrity_db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: .
    container_name: celebot_api
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    # Перенаправляем БД на контейнер db
    environment:
      - DATABASE_URL=postgresql://celebot_admin:meow-password@db:5432/celebrity_db
    command: python app.py
    ports:
      - "8000:8000"

  bot:
    build: .
    container_name: celebot_bot
    env_file: .env
    depends_on:
      - db
      - api
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://celebot_admin:meow-password@db:5432/celebrity_db
    command: python -u bot.py

volumes:
  data:
